
        name: 'my_dbt_project'
        version: '1.0'
        config-version: 2

        profile: 'your_profile_name'

        target-path: "target"
        clean-targets:
        - "target"
        - "dbt_modules"
        